"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$sudo\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$character"""

right_format = '$rust$golang$terraform$docker_context$python$docker_context$nodejs' 

[hostname]
ssh_only = true
format = '[$hostname](bold yellow) '
trim_at = "."
disabled = false

[aws]
symbol = " "

[cmd_duration]
disabled = true

[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true
style = "bold italic blue"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

[env_var]
disabled = false

[git_branch]
symbol = " "

[golang]
symbol = ""
format = ' $symbol ($version) ($style) '

[lua]
disabled = true

[mise]
disabled = false

[nodejs]
symbol = ""
format = ' [$symbol ($version)]($style)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[os]
disabled = true

[python]
symbol = " "
format = '[${symbol}python (${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
format = ' $symbol ($version) ($style) '

[terraform]
disabled = false
