"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$sudo
$directory\
$git_branch\
$git_status\
$git_state\
$character"""

right_format = """
$aws\
$kubernetes\
$python\
$nodejs\
$golang\
$rust\
$terraform\
$docker_context\
$mise"""

[aws]
disabled = false

[cmd_duration]
disabled = true

[directory]
style = "blue"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
disabled = false

[env_var]
disabled = false

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](219) ($ahead_behind$stashed)]($style) "
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
symbol = ""
format = ' $symbol ($version) ($style) '

[lua]
disabled = true

[mise]
disabled = false

[nodejs]
symbol = " "
format = ' $symbol ($version) ($style)'

[os]
disabled = true

[python]
disabled = false

[rust]
symbol = ""
format = ' $symbol ($version) ($style) '

[terraform]
disabled = false
